### ISSUE TITLE
없는 endpoint에서 200 OK 발생

### ISSUE THREAD

**Issue by sukjuhong** [Alpha-e-Um/Backend#14]
## Feature Description

원래 없는 Endpoint에서 404 Not found가 정상인데 나오지 않음.

## Detailed Tasks

- [x] 200 OK 나오는 원인 파악
- [x] 코드 수정

## Reference Materials (Optional)

![image](https://github.com/Alpha-e-Um/Backend/assets/102505374/7a22ba53-e4ec-47fb-a628-f20ae8c8b480)

**Comment by mclub4** [comment]
https://stackoverflow.com/questions/56722709/request-not-reaching-to-the-controller-but-still-get-200-response

https://stackoverflow.com/questions/60025207/spring-boot-rest-api-accepts-all-requests-and-returns-blank-responses

위에 두 글 참고하면 좋을듯. 

JwtAuthenticationFilter.Class에서

```java
try {
            if (StringUtils.hasText(token) && tokenProvider.validateToken(token)) {
                Authentication authentication = tokenProvider.getAuthentication(token);
                SecurityContextHolder.getContext().setAuthentication(authentication);
            }
        } catch (JwtTokenInvalidException jwtTokenInvalidException) {
            request.setAttribute(ATTRIBUTE_TOKEN_ERROR, jwtTokenInvalidException);
        }

        filterChain.doFilter(request, response);
```
에서
```java
try {
            if (StringUtils.hasText(token) && tokenProvider.validateToken(token)) {
                Authentication authentication = tokenProvider.getAuthentication(token);
                SecurityContextHolder.getContext().setAuthentication(authentication);
            }
            else filterChain.doFilter(request, response);
        } catch (JwtTokenInvalidException jwtTokenInvalidException) {
            request.setAttribute(ATTRIBUTE_TOKEN_ERROR, jwtTokenInvalidException);
        }

        filterChain.doFilter(request, response);
```
로 변경하면 해결이 됨. 근데 이유는 잘 모르겠음. if문에 안걸려도 try catch 통과하고 마지막에 filterChain 실행될텐데 왜 else를 추가해야 작동하는지 잘 모르겠네...?

문제해결이랑 코드 수정은 했지만... 이유는 명확하지 않아서 이슈는 안닫을게

**Comment by sukjuhong** [comment]
![image](https://github.com/Alpha-e-Um/Backend/assets/102505374/2d257c96-2298-4a17-8e2a-fd334e5f5ae1)

현재 500 No static resource가 발생하는 문제로 전환되었습니다

**Comment by sukjuhong** [comment]
@mclub4

디버깅을 통해 ResourceHttpRequestHandler에서 해당 endpoint에 해당하는 resource를 찾고 있는 것을 알았습니다.

```java
	@Override
	public void handleRequest(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		// For very general mappings (e.g. "/") we need to check 404 first
		Resource resource = getResource(request);
		if (resource == null) {
			logger.debug("Resource not found");
			throw new NoResourceFoundException(HttpMethod.valueOf(request.getMethod()), getPath(request));
		}
        }
```

따라서 `spring.web.resources.add-mappings=false`를 properties에 추가하여 handler를 제거했고, 해당 오류가 NoHandlerFountException으로 변경되어

```java
    @ExceptionHandler(NoHandlerFoundException.class)
    @ResponseStatus(HttpStatus.NOT_FOUND)
    public ResponseEntity<ErrorResponse> handle404(NoHandlerFoundException e){
        return ResponseEntity
                .status(e.getStatusCode())
                .body(ErrorResponse.builder()
                        .status(e.getStatusCode().value())
                        .message(e.getMessage())
                        .build());
    }
```

CustomExceptionHandler에 해당 부분을 추가하여 404 오류를 응답하도록 수정해서 해결했습니다.

**Comment by mclub4** [comment]
![image](https://github.com/Alpha-e-Um/Backend/assets/55117706/7b97910d-b313-4695-a878-40c195697725)

해당 오류 build해서 jar로 실행하면 또 발생함.

**Comment by mclub4** [comment]
죄송합니다. 제 로컬 환경설정 오류였어요. 테스트 한다고 아래 구문 지워서 발생한거였어요.

spring.h2.console.enabled=true
