### ISSUE TITLE
H2-Console 먹통

### ISSUE THREAD

**Issue by mclub4** [Alpha-e-Um/Backend#18]
## What is the bug?

h2-console이 두개 뜹니다.

## Under what circumstances does the bug occur?

develop pull 받은 뒤로 뜹니다.... 일단 올리고 오류 로그는 좀 이따 자세히 살펴보겠습니다.

## Expected Result

h2-console이 먹통이 되어서 아무것도 작동하지 않습니다.

## Reference Materials (Optional)
![image](https://github.com/Alpha-e-Um/Backend/assets/55117706/c5ddd491-ee54-45f3-b2bf-0dc76a085407)

![image](https://github.com/Alpha-e-Um/Backend/assets/55117706/c5832480-8320-44cf-9ba2-ba8c6cca03df)

**Comment by sukjuhong** [comment]
![image](https://github.com/Alpha-e-Um/Backend/assets/102505374/c4bb981b-7585-4777-a498-2896ee98c98d)

develop branch인데 전 하나네요..? 다시 한번 확인 부탁드려요~

**Comment by mclub4** [comment]
해결 불가능... 도저히 이유를 알 수가 없음...
