### ISSUE TITLE
resume mapping 오류

### ISSUE THREAD

**Issue by sukjuhong** [Alpha-e-Um/Backend#55]
## Feature Description

현재 gradle build시에 등장하는 오류들이 있습니다.

![image](https://github.com/Alpha-e-Um/Backend/assets/102505374/536aa53d-a5bb-4289-a534-6e575c77c2d1)

## Detailed Tasks

- [ ] 오류 해결

**Comment by mclub4** [comment]
Mapper에서 ignore를 제대로 명시해주지 않아서 발생하는 경고네요. 추후 수정하겠습니다.
